---
title: Code a carol
hero_image: images/banner.png
description: Code the song 'Twelve Days of Christmas' using Sonic Pi
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: music
technologies: sonic-pi
site_areas: projects
hardware: ''
software: sonic-pi
version: 4
last_tested: 2017-12-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: Decomposition
- title: Code the introduction
- title: Speed and synths
- title: Code the partridge
- title: Code the other parts
- title: 'Challenge: code the song'
- title: The song step by step
  completion: internal
- title: 'Challenge: your own song'
